package labsoft;
// Generated 07/11/2015 01:44:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Software generated by hbm2java
 */
public class Software  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String versao;
     private Set<CadLabSoft> labSofts = new HashSet<CadLabSoft>(0);

    public Software() {
    }

    public Software(Integer id, String nome, String versao) {
        this.id = id;
        this.nome = nome;
        this.versao = versao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getVersao() {
        return this.versao;
    }
    
    public void setVersao(String versao) {
        this.versao = versao;
    }

    public Set<CadLabSoft> getLabSofts() {
        return labSofts;
    }

    public void setLabSofts(Set<CadLabSoft> labSofts) {
        this.labSofts = labSofts;
    }
    
}


